apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-central-station-deployment
  labels:
    app: base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base
  template:
    metadata:
      labels:
        app: base
    spec:
      volumes:
        - name: base-storage
          persistentVolumeClaim:
            claimName: archive-persistent-volume-claim
      containers:
        - name: base-central-station
          env:
            - name: BATCH_SIZE
              value: "10000"
          image: base-central-station-image:latest
          volumeMounts:
            - name: base-storage
              mountPath: /archive
              subPath: archive
            - name: base-storage
              mountPath: /bitCaskStore
              subPath: bitCaskStore
          imagePullPolicy: Never