apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-deployment
  labels:
    component: station

spec:
  replicas: 2
  selector:
    matchLabels:
      component: station
  template:
    metadata:
      labels:
        component: station
    spec:
      containers:
        - name: weather-station-container
          image: weather-station-image:latest
          imagePullPolicy: Never
          env:
            - name: stationType
              value: "Mock"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-meteo-weather-station-deployment
  labels:
    component: om-station

spec:
  replicas: 1
  selector:
    matchLabels:
      component: om-station
  template:
    metadata:
      labels:
        component: om-station
    spec:
      containers:
        - name: om-weather-station-container
          image: weather-station-image:latest
          imagePullPolicy: Never
          env:
            - name: stationType
              value: "OM"
            - name: longitudeOM
              value: "21.256"
            - name: latitudeOM
              value: "31.78"
