apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-deployment
  labels:
    component: station

spec:
  replicas: 1
  selector:
    matchLabels:
      component: station
  template:
    metadata:
      labels:
        component: station
    spec:
      containers:
        - name: weather-station-container
          image: weather-station-image
          imagePullPolicy: Never
          env:
            - name: stationType
              value: "Mock"